name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: "0"
    
      - name: Merge pre_master into master
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout master
          git merge pre_master
          git push -u origin master

      - name: Run pytest on server
        run: |
          cd C:\Users\llorenc.buil\Documents\GitHub-Actions\GitHub-Actions
          pytest

      - name: Pull code
        run: |
          cd C:\Users\llorenc.buil\Documents\GitHub-Actions\GitHub-Actions
          git pull
