name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print greeting
        run: echo 'hey'

      - name: Identify with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: "0"
    
      - name: Merge pre_master into master
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout master
          git merge pre_master
          git push -u origin master
