name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Clone code to VM
        uses: actions/checkout@v3
        with:
          # only take last commit (to reduce time)
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest on dev
        run: |
          pytest

      - name: Identify with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Merge dev into pre_master
        # if tests are passed, dev is merged into pre_master
        if: ${{ success() }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout pre_master
          git merge dev
          git push -u origin pre_master

      - name: Run pytest on pre_master
        run: |
          pytest