name: Pipeline

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code to VM
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # only take last commit (to reduce time)

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest

      - name: Identify with token
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: "0"

      - name: Merge dev into master
        if: ${{ success() }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout master
          git merge -Xtheirs dev
          git push -u origin master