name: Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: "0"

      - name: Print greeting
        run: |
          cd C:\Users\llorenc.buil\Documents\GitHub-Actions\GitHub-Actions
          git pull